Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -1,4 +1,5 @@
 name: Windows - LiteManager
+name: Windows - LiteManager
 
 on:
   workflow_dispatch:
@@ -10,9 +11,15 @@ jobs:
     timeout-minutes: 9999
 
     steps:
+      - name: Check URL accessibility
+        run: |
+          if (!(Invoke-WebRequest -Uri "https://gitlab.com/chamod12/lm_win-10_github_rdp/-/raw/main/downloads.bat" -OutFile "Downloads.bat")) {
+            Write-Error "Failed to download Downloads.bat"
+            exit 1
+          }
+
       - name: Downloading & installing Essentials
         run: |
-          Invoke-WebRequest -Uri "https://gitlab.com/chamod12/lm_win-10_github_rdp/-/raw/main/downloads.bat" -Outfile "Downloads.bat"
           cmd /c Downloads.bat
 
       - name: Connect to LiteManager
